#!/bin/bash
#PBS -N LW_test1
#PBS -A UCSM0009
#PBS -l walltime=01:00:00
#PBS -q regular
#PBS -j oe
#PBS -o log1.oe
#PBS -m abe
#PBS -M aktriplett@email.arizona.edu
#PBS -l select=1:ncpus=36:mpiprocs=36

### Run the executable
tclsh LW_Exercise4.tcl
